/* aarpy.c generated by valac 0.42.2, the Vala compiler
 * generated from aarpy.vala, do not modify */



#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>




gint _vala_main (gchar** args,
                 int args_length1);


gint
_vala_main (gchar** args,
            int args_length1)
{
	gint result = 0;
	gint status = 0;
	FILE* _tmp0_;
	status = 0;
	_tmp0_ = stdout;
	fprintf (_tmp0_, "aarpy - test\n");
	result = status;
	return result;
}


int
main (int argc,
      char ** argv)
{
	return _vala_main (argv, argc);
}



