/* Network.c generated by valac 0.42.2, the Vala compiler
 * generated from Network.vala, do not modify */



#include <glib.h>
#include <glib-object.h>


#define TYPE_NETWORK (network_get_type ())
#define NETWORK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_NETWORK, Network))
#define NETWORK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_NETWORK, NetworkClass))
#define IS_NETWORK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_NETWORK))
#define IS_NETWORK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_NETWORK))
#define NETWORK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_NETWORK, NetworkClass))

typedef struct _Network Network;
typedef struct _NetworkClass NetworkClass;
typedef struct _NetworkPrivate NetworkPrivate;
enum  {
	NETWORK_0_PROPERTY,
	NETWORK_NUM_PROPERTIES
};
static GParamSpec* network_properties[NETWORK_NUM_PROPERTIES];

struct _Network {
	GObject parent_instance;
	NetworkPrivate * priv;
};

struct _NetworkClass {
	GObjectClass parent_class;
};


static gpointer network_parent_class = NULL;

GType network_get_type (void) G_GNUC_CONST;
Network* network_new (void);
Network* network_construct (GType object_type);


Network*
network_construct (GType object_type)
{
	Network * self = NULL;
	self = (Network*) g_object_new (object_type, NULL);
	return self;
}


Network*
network_new (void)
{
	return network_construct (TYPE_NETWORK);
}


static void
network_class_init (NetworkClass * klass)
{
	network_parent_class = g_type_class_peek_parent (klass);
}


static void
network_instance_init (Network * self)
{
}


/**************************************************************************
* AUTHOR: Jorel Paddick
* FILE NAME: Network.vala
* CREATED: 06-11-2018
* MODIFIED:                                                                
* PURPOSE: Defines a class for representing a network of Clients
***************************************************************************/
GType
network_get_type (void)
{
	static volatile gsize network_type_id__volatile = 0;
	if (g_once_init_enter (&network_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (NetworkClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) network_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Network), 0, (GInstanceInitFunc) network_instance_init, NULL };
		GType network_type_id;
		network_type_id = g_type_register_static (G_TYPE_OBJECT, "Network", &g_define_type_info, 0);
		g_once_init_leave (&network_type_id__volatile, network_type_id);
	}
	return network_type_id__volatile;
}



